address: localhost
port: 9292
servers: 1
max_conns: 1024
max_persistent_conns: 512
timeout: 30
environment: production
pid: /tmp/pids/thin-bookmarks-production.pid
log: /tmp/log/thin-bookmarks-production.log
daemonize: true
